### ISSUE TITLE
Split codeql scanning such that it only runs dependabot changes on pull_request

### ISSUE THREAD

**Issue by melink14** [melink14/rikaikun#398]
dependabot doesn't play well with codeql. During pull requests, the push action fails due to coming too quickly after PR action, and during merge it fails do to being read only.

We should make https://github.com/melink14/rikaikun/blob/master/.github/workflows/codeql-analysis.yml a composite action and have one workflow for Dependabot on pull_request and one for not dependabot on push/pr/cron.

Composite action docs:
https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

Example actor filtering in actions:
```
on: [pull_request]
jobs:
  job1:
    if: github.actor!= 'dependabot-preview[bot]'   # ignore the pull request which comes from user depbot.
```

Example error message:

> Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
